name: 'coverage'
on:
    pull_request_target:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  test-script: 'yarn test:app'
                  package-manager: yarn
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 65